### ISSUE TITLE
configuration form always shows 1 GB as threshold

### ISSUE THREAD

**Issue by dirk-thomas** [mthak/diskcheck-plugin#1]
When saving the system configuration form with a value different that `1` for the `Threshold for disk Check` it correctly write that value to the configuration file `diskcheck.xml`. But when reloading the form the value in the input field shows `1` again.

I am not sure which value the plugin is then using for the check.

**Comment by mthak** [comment]
The plugin will pick the value from the xml, Please raise a Jira , i will
look into this and fix it in a day or two,

Thanks
Manoj

**Comment by dirk-thomas** [comment]
The `diskcheck` plugin is not yet available as a component in Jira. So currently I can't select a reasonable component which is required.

**Comment by mthak** [comment]
this is fixed in latest release 0.24, Please check and let me know if you
still face any issues,

Thanks
Manoj

**Comment by dirk-thomas** [comment]
I can confirm that the form gets populated correctly with the current value with version 0.24. Thank you!

Should I fill further ticket here at GitHub or are you going to add a "diskcheck-plugin" component to the Jenkins Jira instance in the near future?

**Comment by mthak** [comment]
Dirk,

I have asked the admins to add the component in Jira , feel free to reach out via github if you don't find the component in Jira
